//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManager.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERPRODUCT
    {
        public int USERID { get; set; }
        public string PRODUCTNUMBER { get; set; }
        public int ID { get; set; }
    
        public virtual APPUSER APPUSER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
